
[nitpick.meta]
name = "Shell style compilation"

[nitpick.styles]
include = [
    "gh://AntarktisZ11/Nitpick/Shell/bashate.toml",
    "gh://AntarktisZ11/Nitpick/Shell/shellcheck.toml",
    "gh://AntarktisZ11/Nitpick/Shell/shfmt.toml",
]
