[nitpick.meta]
name = "Darglint, linter for python docstrings"
url = "https://github.com/terrencepreilly/darglint"

["setup.cfg".darglint]
strictness = "short"
docstring_style = "google"
message_template = '"{path}:{line} -> {msg_id} {msg}"'

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/terrencepreilly/darglint"
rev = ""

[[".pre-commit-config.yaml".repos.hooks]]
id = "darglint"
args = [
    "-z",
    "short",
    "-s",
    "google",
    "-m",
    '"{path}:{line} -> {msg_id} {msg}"',
]
