[nitpick.meta]
name = "isort"
url = "https://github.com/PyCQA/isort"

["pyproject.toml".tool.isort]
src_paths = ["**"]
line_length = 60
skip = ".tox,build"
known_first_party = "tests"

# The configuration below is needed for compatibility with black.
# https://github.com/python/black#how-black-wraps-lines
# https://github.com/PyCQA/isort#multi-line-output-modes
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

# Heading per import section
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third-Party"
import_heading_firstparty = "First-Party"
import_heading_localfolder = "Local Folder"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/isort"

[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"
