[nitpick.meta]
name = "Preset for Python 3.7"
url = "https://github.com/AntarktisZ11/Nitpick"

style = [
    'gh://AntarktisZ11/Nitpick/pre-commit-hooks.toml',
    'gh://AntarktisZ11/Nitpick/black.toml',
    'gh://AntarktisZ11/Nitpick/isort.toml',
    'gh://AntarktisZ11/Nitpick/mypy.toml',
    'gh://AntarktisZ11/Nitpick/file-structure.toml',
    'py://nitpick/resources/python/37',
    'gh://AntarktisZ11/Nitpick/commitizen.toml',
    'gh://AntarktisZ11/Nitpick/Shell/shell-style.toml',
]
