[nitpick.meta]
name = "PyUpgrade"
url = "https://github.com/asottile/pyupgrade"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = ""

[[".pre-commit-config.yaml".repos.hooks]]
id = "pyupgrade"
args = ["--py37-plus"]
